apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-pod
  template:
    metadata:
      labels:
        app: cicd-pod
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: cicd
        image: dockerwithsaurabh/cicd:latest
        ports:
        - containerPort: 4000  # match your Node.js app
---
apiVersion: v1
kind: Service
metadata: 
  name: cicd-deploy-service
spec:
  type: LoadBalancer
  selector:
    app: cicd-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000


    